// <auto-generated />
using System;
using ARJE.Api.Entidades;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ARJE.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261001165548_AddPrioridadReporte")]
    partial class AddPrioridadReporte
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ARJE.Api.Entidades.Cuadrilla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstatusDisponibilidad")
                        .HasColumnType("int");

                    b.Property<string>("Integrantes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UsuarioApp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EstatusDisponibilidad");

                    b.HasIndex("UsuarioApp")
                        .IsUnique();

                    b.ToTable("Cuadrillas");
                });

            modelBuilder.Entity("ARJE.Api.Entidades.Evidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Archivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaCaptura")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdReporte")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdReporte");

                    b.ToTable("Evidencias");
                });

            modelBuilder.Entity("ARJE.Api.Entidades.Reporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("ConfianzaIA")
                        .HasColumnType("float");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Estatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("FechaRecibido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("IdCuadrillaAsignada")
                        .HasColumnType("int");

                    b.Property<int?>("IdCuadrillaSupervisora")
                        .HasColumnType("int");

                    b.Property<string>("JustificacionPrioridad")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("decimal(18,15)");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("decimal(18,15)");

                    b.Property<string>("NombreCiudadano")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroContrato")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Prioridad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<string>("RazonamientoIA")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double?>("ScorePrioridad")
                        .HasColumnType("float");

                    b.Property<string>("TelefonoCiudadano")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("TiempoEstimado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoProblema")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Estatus");

                    b.HasIndex("IdCuadrillaAsignada");

                    b.HasIndex("IdCuadrillaSupervisora");

                    b.HasIndex("Prioridad");

                    b.HasIndex("Latitud", "Longitud");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("ARJE.Api.Entidades.SeguimientoUbicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCuadrilla")
                        .HasColumnType("int");

                    b.Property<int>("IdReporte")
                        .HasColumnType("int");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("decimal(18,15)");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("decimal(18,15)");

                    b.HasKey("Id");

                    b.HasIndex("FechaHora");

                    b.HasIndex("IdCuadrilla");

                    b.HasIndex("IdReporte");

                    b.ToTable("SeguimientosUbicacion");
                });

            modelBuilder.Entity("ARJE.Api.Entidades.UsuarioSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Rol");

                    b.HasIndex("Usuario")
                        .IsUnique();

                    b.ToTable("UsuariosSistema");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Administrador",
                            PasswordHash = "$2a$11$RxMNHoXITr575Hq/v4iSpO3ynDFjkjRelm7FoeJ0rWfC43WMfNtLi",
                            Rol = 1,
                            Usuario = "admin"
                        });
                });

            modelBuilder.Entity("ARJE.Api.Entidades.Evidencia", b =>
                {
                    b.HasOne("ARJE.Api.Entidades.Reporte", "Reporte")
                        .WithMany("Evidencias")
                        .HasForeignKey("IdReporte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reporte");
                });

            modelBuilder.Entity("ARJE.Api.Entidades.Reporte", b =>
                {
                    b.HasOne("ARJE.Api.Entidades.Cuadrilla", "CuadrillaAsignada")
                        .WithMany("ReportesAsignados")
                        .HasForeignKey("IdCuadrillaAsignada")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ARJE.Api.Entidades.Cuadrilla", "CuadrillaSupervisora")
                        .WithMany("ReportesSupervisados")
                        .HasForeignKey("IdCuadrillaSupervisora")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CuadrillaAsignada");

                    b.Navigation("CuadrillaSupervisora");
                });

            modelBuilder.Entity("ARJE.Api.Entidades.SeguimientoUbicacion", b =>
                {
                    b.HasOne("ARJE.Api.Entidades.Cuadrilla", "Cuadrilla")
                        .WithMany("SeguimientosUbicacion")
                        .HasForeignKey("IdCuadrilla")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ARJE.Api.Entidades.Reporte", "Reporte")
                        .WithMany("SeguimientosUbicacion")
                        .HasForeignKey("IdReporte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuadrilla");

                    b.Navigation("Reporte");
                });

            modelBuilder.Entity("ARJE.Api.Entidades.Cuadrilla", b =>
                {
                    b.Navigation("ReportesAsignados");

                    b.Navigation("ReportesSupervisados");

                    b.Navigation("SeguimientosUbicacion");
                });

            modelBuilder.Entity("ARJE.Api.Entidades.Reporte", b =>
                {
                    b.Navigation("Evidencias");

                    b.Navigation("SeguimientosUbicacion");
                });
#pragma warning restore 612, 618
        }
    }
}
