import {
  TipoProblema,
  EstatusReporte,
  EstatusCuadrilla,
  RolUsuario,
  ReporteDetalleDTO,
  CuadrillaDTO,
  UsuarioDTO,
  DashboardMetricsDTO,
  GraficaMesDTO,
  CategoriaCountDTO,
  CuadrillaRendimientoDTO,
  TipoEvidencia,
} from '../types';

import fugaImg from '../assets/fuga-ejemplo.png';

export const MOCK_ADMIN_USER: UsuarioDTO = {
  id: 1,
  nombre: 'Administrador General ARJE',
  usuario: 'admin',
  rol: RolUsuario.Administrador,
  activo: true,
};

export const INITIAL_CUADRILLAS: CuadrillaDTO[] = [
  {
    id: 1,
    nombre: 'Cuadrilla Norte',
    integrantes: 'Juan Pérez (Líder), Carlos Rivas, Pedro Ruiz',
    usuarioApp: 'cuadrilla.norte',
    estatusDisponibilidad: EstatusCuadrilla.Ocupada,
    reportesActivosCount: 2,
    telefonoContacto: '449-102-3948',
    vehiculo: 'Camioneta Ford Ranger #04',
  },
  {
    id: 2,
    nombre: 'Cuadrilla Centro',
    integrantes: 'Miguel Morales (Líder), Roberto Sosa',
    usuarioApp: 'cuadrilla.centro',
    estatusDisponibilidad: EstatusCuadrilla.Disponible,
    reportesActivosCount: 0,
    telefonoContacto: '449-234-8591',
    vehiculo: 'Chevrolet Silverado #02',
  },
  {
    id: 3,
    nombre: 'Cuadrilla Oriente',
    integrantes: 'Esteban Gómez (Líder), Luis Prado, Marco Antonio',
    usuarioApp: 'cuadrilla.oriente',
    estatusDisponibilidad: EstatusCuadrilla.Disponible,
    reportesActivosCount: 0,
    telefonoContacto: '449-345-9602',
    vehiculo: 'Camioneta Nissan NP300 #08',
  },
  {
    id: 4,
    nombre: 'Cuadrilla Sur',
    integrantes: 'Jorge Castillo (Líder), Daniel Lara',
    usuarioApp: 'cuadrilla.sur',
    estatusDisponibilidad: EstatusCuadrilla.Ocupada,
    reportesActivosCount: 1,
    telefonoContacto: '449-456-0713',
    vehiculo: 'Camioneta RAM 1500 #05',
  },
  {
    id: 5,
    nombre: 'Cuadrilla Poniente',
    integrantes: 'Fernando Silva (Líder), Mario Vega',
    usuarioApp: 'cuadrilla.poniente',
    estatusDisponibilidad: EstatusCuadrilla.Ocupada,
    reportesActivosCount: 1,
    telefonoContacto: '449-567-1824',
    vehiculo: 'Camioneta Hilux #07',
  },
  {
    id: 6,
    nombre: 'Cuadrilla de Fugas Mayores',
    integrantes: 'Ricardo Méndez (Especialista), Andrés Cruz, Héctor Valenzuela',
    usuarioApp: 'cuadrilla.fugas',
    estatusDisponibilidad: EstatusCuadrilla.Disponible,
    reportesActivosCount: 0,
    telefonoContacto: '449-678-2935',
    vehiculo: 'Camión Cisterna y Vactor #01',
  },
  {
    id: 7,
    nombre: 'Cuadrilla Nocturna',
    integrantes: 'Gabriel Ortega (Líder), Samuel Fuentes',
    usuarioApp: 'cuadrilla.nocturna',
    estatusDisponibilidad: EstatusCuadrilla.Disponible,
    reportesActivosCount: 0,
    telefonoContacto: '449-789-3046',
    vehiculo: 'Unidad de Respuesta Rápida #11',
  },
];

export const INITIAL_REPORTES: ReporteDetalleDTO[] = [
  {
    id: 89,
    folio: 'FOL-2023-89',
    tipoProblema: TipoProblema.Fuga,
    categoria: 'Fuga en vía pública',
    confianzaIA: 0.95,
    razonamientoIA: 'Ruptura evidente en red hidráulica principal sobre calle con afectación al pavimento vehicular.',
    descripcion: 'Se detectó una fuga de agua en la tubería principal de la calle Hidalgo #142. El vecino reporta que el agua lleva brotando desde la madrugada y ya afecta el pavimento.',
    latitud: 21.8853,
    longitud: -102.2916,
    direccion: 'Calle Miguel Hidalgo #142, Zona Centro, Aguascalientes',
    fechaRecibido: '2026-09-24T08:34:00Z',
    estatus: EstatusReporte.EnProceso,
    tiempoEstimado: 45,
    idCuadrillaAsignada: 1,
    cuadrillaAsignadaNombre: 'Cuadrilla Norte',
    numeroContrato: '123456',
    nombreCiudadano: 'Martín Rodríguez',
    telefonoCiudadano: '449-912-3456',
    totalEvidencias: 1,
    prioridad: 'Critica',
    scorePrioridad: 0.94,
    justificacionPrioridad: 'Fuga mayor en tubería principal afectando carpeta asfáltica con riesgo de socavón e interrupción del servicio.',
    evidencias: [
      {
        id: 101,
        tipo: TipoEvidencia.Inicial,
        archivoUrl: fugaImg,
        fechaCaptura: '2026-09-24T08:35:10Z',
      },
    ],
    seguimientosUbicacion: [
      {
        id: 201,
        idCuadrilla: 1,
        cuadrillaNombre: 'Cuadrilla Norte',
        latitud: 21.8854,
        longitud: -102.2915,
        fechaRegistro: '2026-09-24T09:10:00Z',
      },
    ],
  },
  {
    id: 45,
    folio: 'FOL-2023-45',
    tipoProblema: TipoProblema.FaltaAbastecimiento,
    categoria: 'Baja presión del agua',
    confianzaIA: 0.91,
    razonamientoIA: 'Reporte de flujo insuficiente durante horario habitual en red de distribución secundaria.',
    descripcion: 'Baja presión de agua durante más de 3 días consecutivos en el sector norte del fraccionamiento.',
    latitud: 21.912,
    longitud: -102.285,
    direccion: 'Av. Adolfo López Mateos #504, Col. San Marcos',
    fechaRecibido: '2026-09-23T14:15:00Z',
    estatus: EstatusReporte.Cerrado,
    tiempoEstimado: 120,
    idCuadrillaAsignada: 2,
    cuadrillaAsignadaNombre: 'Cuadrilla Centro',
    numeroContrato: '482910',
    nombreCiudadano: 'Laura Gómez',
    telefonoCiudadano: '449-345-6789',
    totalEvidencias: 1,
    prioridad: 'Media',
    scorePrioridad: 0.52,
    justificacionPrioridad: 'Baja presión prolongada pero con suministro parcial activo en la zona.',
    fechaResolucion: '2026-09-23T17:40:00Z',
    comentariosResolucion: 'Se reemplazó la válvula reguladora de presión en el manifold secundario. Presión restablecida a 2.4 bar.',
    evidencias: [],
    seguimientosUbicacion: [],
  },
  {
    id: 31,
    folio: 'FOL-2023-31',
    tipoProblema: TipoProblema.InstalacionRota,
    categoria: 'Medidor dañado',
    confianzaIA: 0.88,
    razonamientoIA: 'Falla física y filtración en el cuadro del medidor de consumo domiciliario.',
    descripcion: 'Medidor roto y fuga en el cuadro de toma domiciliaria. Fuga constante hacia la banqueta.',
    latitud: 21.871,
    longitud: -102.305,
    direccion: 'Calle República de Brasil #302, Fracc. Las Américas',
    fechaRecibido: '2026-09-24T10:05:00Z',
    estatus: EstatusReporte.Nuevo,
    tiempoEstimado: undefined,
    idCuadrillaAsignada: null,
    cuadrillaAsignadaNombre: null,
    numeroContrato: '592014',
    nombreCiudadano: 'Fernando Rangel',
    telefonoCiudadano: '449-567-8901',
    totalEvidencias: 0,
    prioridad: 'Alta',
    scorePrioridad: 0.78,
    justificacionPrioridad: 'Medidor roto con derrame continuo sobre banqueta peatonal y desperdicio no cuantificado.',
    evidencias: [],
    seguimientosUbicacion: [],
  },
  {
    id: 92,
    folio: 'FOL-2023-92',
    tipoProblema: TipoProblema.UsoIndebido,
    categoria: 'Uso indebido',
    confianzaIA: 0.85,
    razonamientoIA: 'Lavado con manguera de alta presión en giro comercial fuera del horario permitido.',
    descripcion: 'Lavado excesivo con manguera a presión en comercio automotriz durante horario restringido.',
    latitud: 21.895,
    longitud: -102.274,
    direccion: 'Av. Convención de 1914 #812, Col. Circunvalación',
    fechaRecibido: '2026-09-24T11:20:00Z',
    estatus: EstatusReporte.LevantandoInformacion,
    tiempoEstimado: 30,
    idCuadrillaAsignada: 4,
    cuadrillaAsignadaNombre: 'Cuadrilla Sur',
    numeroContrato: '782910',
    nombreCiudadano: 'Denuncia Ciudadana Anónima',
    telefonoCiudadano: null,
    totalEvidencias: 1,
    prioridad: 'Baja',
    scorePrioridad: 0.25,
    justificacionPrioridad: 'Uso indebido sin daño estructural inmediato ni afectación a la red hidráulica.',
    evidencias: [],
    seguimientosUbicacion: [],
  },
  {
    id: 95,
    folio: 'FOL-2023-95',
    tipoProblema: TipoProblema.Fuga,
    categoria: 'Fuga en vía pública',
    confianzaIA: 0.96,
    razonamientoIA: 'Impacto vehicular con desprendimiento de acometida y pérdida de agua potable en camellón.',
    descripcion: 'Fuga considerable de agua potable en camellón central tras impacto vehicular.',
    latitud: 21.928,
    longitud: -102.268,
    direccion: 'Blvd. Luis Donaldo Colosio #120, Valle de las Trojes',
    fechaRecibido: '2026-09-24T12:00:00Z',
    estatus: EstatusReporte.EnProceso,
    tiempoEstimado: 90,
    idCuadrillaAsignada: 5,
    cuadrillaAsignadaNombre: 'Cuadrilla Poniente',
    numeroContrato: '601928',
    nombreCiudadano: 'C5i Emergencias',
    telefonoCiudadano: '911',
    totalEvidencias: 2,
    prioridad: 'Critica',
    scorePrioridad: 0.96,
    justificacionPrioridad: 'Impacto vehicular sobre vialidad primaria con pérdida torrencial de agua e inundación en carril central.',
    evidencias: [
      {
        id: 102,
        tipo: TipoEvidencia.Inicial,
        archivoUrl: fugaImg,
        fechaCaptura: '2026-09-24T12:02:15Z',
      },
    ],
    seguimientosUbicacion: [],
  },
  {
    id: 98,
    folio: 'FOL-2023-98',
    tipoProblema: TipoProblema.InstalacionRota,
    categoria: 'Registro dañado o sin tapa',
    confianzaIA: 0.89,
    razonamientoIA: 'Tapa de registro ausente sobre paso peatonal representando riesgo físico.',
    descripcion: 'Tapa de alcantarilla de red de agua sin asegurar sobre paso peatonal.',
    latitud: 21.865,
    longitud: -102.312,
    direccion: 'Calle Madero esq. Galeana, Zona Centro',
    fechaRecibido: '2026-09-24T13:45:00Z',
    estatus: EstatusReporte.Nuevo,
    tiempoEstimado: undefined,
    idCuadrillaAsignada: null,
    cuadrillaAsignadaNombre: null,
    numeroContrato: '901234',
    nombreCiudadano: 'Claudia Estrada',
    telefonoCiudadano: '449-789-0123',
    totalEvidencias: 0,
    prioridad: 'Alta',
    scorePrioridad: 0.82,
    justificacionPrioridad: 'Registro abierto en crucero peatonal concurrido del centro histórico; riesgo físico para transeúntes.',
    evidencias: [],
    seguimientosUbicacion: [],
  },
  {
    id: 104,
    folio: 'FOL-2023-104',
    tipoProblema: TipoProblema.FaltaAbastecimiento,
    categoria: 'Falta de abastecimiento',
    confianzaIA: 0.94,
    razonamientoIA: 'Interrupción completa de suministro en privada residencial.',
    descripcion: 'Corte imprevisto en el suministro sin previo aviso a la privada.',
    latitud: 21.905,
    longitud: -102.325,
    direccion: 'Privada San Cayetano #15, San Cayetano',
    fechaRecibido: '2026-09-24T14:10:00Z',
    estatus: EstatusReporte.Asignado,
    tiempoEstimado: 60,
    idCuadrillaAsignada: 1,
    cuadrillaAsignadaNombre: 'Cuadrilla Norte',
    numeroContrato: '839201',
    nombreCiudadano: 'Raúl Trejo',
    telefonoCiudadano: '449-890-1234',
    totalEvidencias: 0,
    prioridad: 'Media',
    scorePrioridad: 0.60,
    justificacionPrioridad: 'Corte imprevisto en privada residencial acotada, programado para verificación de válvula de seccionamiento.',
    evidencias: [],
    seguimientosUbicacion: [],
  },
  {
    id: 110,
    folio: 'FOL-2023-110',
    tipoProblema: TipoProblema.Fuga,
    categoria: 'Fuga domiciliaria',
    confianzaIA: 0.93,
    razonamientoIA: 'Fuga en acometida de cobre de 1/2 pulgada reparada satisfactoriamente.',
    descripcion: 'Fuga reparada con sustitución de codo de cobre de 1/2 pulgada. Listo para inspección de supervisión.',
    latitud: 21.8902,
    longitud: -102.281,
    direccion: 'Calle Zaragoza #405, Zona Centro',
    fechaRecibido: '2026-09-24T07:15:00Z',
    estatus: EstatusReporte.Completado,
    tiempoEstimado: 40,
    idCuadrillaAsignada: 3,
    cuadrillaAsignadaNombre: 'Cuadrilla Oriente',
    idCuadrillaSupervisora: null,
    cuadrillaSupervisoraNombre: null,
    numeroContrato: '334912',
    nombreCiudadano: 'Patricia Esparza',
    telefonoCiudadano: '449-765-4321',
    totalEvidencias: 2,
    prioridad: 'Media',
    scorePrioridad: 0.45,
    justificacionPrioridad: 'Fuga domiciliaria reparada y contenida con éxito, en espera de visita de supervisión.',
    fechaResolucion: '2026-09-24T11:45:00Z',
    comentariosResolucion: 'Se reemplazó la conexión y se purgó la línea. Sin fugas residuales.',
    evidencias: [
      {
        id: 103,
        tipo: TipoEvidencia.Inicial,
        archivoUrl: fugaImg,
        fechaCaptura: '2026-09-24T07:20:00Z',
      },
      {
        id: 104,
        tipo: TipoEvidencia.Resolucion,
        archivoUrl: fugaImg,
        fechaCaptura: '2026-09-24T11:40:00Z',
      },
    ],
    seguimientosUbicacion: [],
  },
];

export const MOCK_DASHBOARD_METRICS: DashboardMetricsDTO = {
  reportesTotales: 128,
  reportesEnProceso: 42,
  reportesPendientes: 15,
  reportesResueltos: 71,
  deltaHoy: 9,
  deltaEnProceso: 3,
  deltaPendientes: -2,
  deltaResueltos: 8,
};

export const MOCK_GRAFICA_MES: GraficaMesDTO[] = [
  { mes: 'Ene', recibidos: 138, resueltos: 130 },
  { mes: 'Feb', recibidos: 124, resueltos: 120 },
  { mes: 'Mar', recibidos: 156, resueltos: 140 },
  { mes: 'Abr', recibidos: 149, resueltos: 144 },
  { mes: 'May', recibidos: 186, resueltos: 165 },
  { mes: 'Jun', recibidos: 204, resueltos: 180 },
  { mes: 'Jul', recibidos: 196, resueltos: 195 },
  { mes: 'Ago', recibidos: 190, resueltos: 197 },
];

export const MOCK_CATEGORIAS: CategoriaCountDTO[] = [
  { categoria: 'Fuga en vía pública', tipoProblema: TipoProblema.Fuga, total: 412, porcentaje: 30.6 },
  { categoria: 'Fuga en toma domiciliaria', tipoProblema: TipoProblema.Fuga, total: 286, porcentaje: 21.3 },
  { categoria: 'Medidor dañado / Instalación rota', tipoProblema: TipoProblema.InstalacionRota, total: 231, porcentaje: 17.2 },
  { categoria: 'Mal uso / Desperdicio de agua', tipoProblema: TipoProblema.UsoIndebido, total: 154, porcentaje: 11.5 },
  { categoria: 'Registro abierto / Alcantarilla', tipoProblema: TipoProblema.Otro, total: 118, porcentaje: 8.8 },
  { categoria: 'Baja presión o sin agua', tipoProblema: TipoProblema.FaltaAbastecimiento, total: 96, porcentaje: 7.1 },
  { categoria: 'Otros reportes técnicos', tipoProblema: TipoProblema.Otro, total: 47, porcentaje: 3.5 },
];

export const MOCK_CUADRILLAS_RENDIMIENTO: CuadrillaRendimientoDTO[] = [
  { idCuadrilla: 1, nombre: 'Cuadrilla Norte', reportesAtendidos: 168, tiempoPromedioMinutos: 48 },
  { idCuadrilla: 2, nombre: 'Cuadrilla Centro', reportesAtendidos: 151, tiempoPromedioMinutos: 42 },
  { idCuadrilla: 3, nombre: 'Cuadrilla Oriente', reportesAtendidos: 139, tiempoPromedioMinutos: 55 },
  { idCuadrilla: 4, nombre: 'Cuadrilla Sur', reportesAtendidos: 124, tiempoPromedioMinutos: 50 },
  { idCuadrilla: 5, nombre: 'Cuadrilla Poniente', reportesAtendidos: 98, tiempoPromedioMinutos: 62 },
  { idCuadrilla: 6, nombre: 'Cuadrilla de fugas mayores', reportesAtendidos: 72, tiempoPromedioMinutos: 85 },
  { idCuadrilla: 7, nombre: 'Cuadrilla nocturna', reportesAtendidos: 60, tiempoPromedioMinutos: 39 },
];
